# Host thì sẽ có các tham số
# type=local | remote | external
#   - local: thì sẽ chạy lệnh kiểm tra trực tiếp
#   - remote: thì sẽ chạy lệnh kiểm tra qua SSH
#   - external: thì là target cần kiểm tra, có thể định nghĩa hoặc không,
#        nếu định nghĩa thì có thể dùng name của target đó để kiểm tra
# ip=192.168.1.10  # IP address or hostname
# port=22  # Port number (chỉ dùng cho remote host)
# user=admin  # Username for SSH login (chỉ dùng cho remote host)
# password=admin123  # Password for SSH login (chỉ dùng cho remote host)
# openServicePorts=80,443  # các port cần kiểm tra nhưng chưa có service hoạt động 
#     trước Khi kiểm tra tới port này sẽ ssh vào host và mở port đó bằng netcat
#     nhiều port ngăn cách bằng dấu phẩy.

# --- HOSTS (nơi chạy lệnh) ---
[HOST:local]
type=local

[HOST:app1]
type=remote
ip=192.168.1.10
port=22
user=admin
password=admin123
openServicePorts=80,443


[HOST:app2]
type=remote
ip=192.168.1.20
# Dùng SSH passwordless

[HOST:db1]
type=remote
ip=192.168.1.30
user=dbadmin

[HOST:db2]
type=remote # có thể dùng cả check kết nối tới cả remote host
ip=192.168.1.31

[HOST:dns]
type=external
ip=8.8.8.8

[HOST:google]
type=external
ip=google.com

[HOST:api]
type=external
ip=api.example.com



# --- CHECKS ---

[CHECK:local]
# check app1
cmd=ping app1
cmd=telnet 192.168.1.10 22 # có thể dùng ip address
cmd=telnet app1 22 # dùng hostname được khai báo trong config
cmd=telnet app1 80 # port 80 sẽ được mở bằng netcat trước khi kiểm tra
cmd=telnet app1 443 # port 443 sẽ được mở bằng netcat trước khi kiểm tra
newline # in ra một dòng mới để phân tách các check
# check app2 
cmd=ping app2
cmd=telnet app2 22
cmd=telnet app2 80
cmd=telnet app2 443
newline # in ra một dòng mới để phân tách các check
# check db1
cmd=ping db1
cmd=telnet db1 3306
newline # in ra một dòng mới để phân tách các check
# check db2
cmd=ping db2
cmd=telnet db2 3306
newline # in ra một dòng mới để phân tách các check

[CHECK:app1]
cmd=ping dns
cmd=telnet dns 53
cmd=curl -X GET https://google.com
cmd=curl -X POST https://api.example.com/login -d '{"user":"admin"}'
newline # in ra một dòng mới để phân tách các check
cmd=ping db1
cmd=telnet db1 3306
newline # in ra một dòng mới để phân tách các check
cmd=ping app2
cmd=telnet app2 22
cmd=telnet app2 80
cmd=telnet app2 443
newline # in ra một dòng mới để phân tách các check

[CHECK:app2]
cmd=ping dns
cmd=telnet dns 53
cmd=curl -X GET https://google.com
cmd=curl -X POST https://api.example.com/login {"user":"admin"}
newline # in ra một dòng mới để phân tách các check
cmd=ping db2
cmd=telnet db2 3306
newline # in ra một dòng mới để phân tách các check
cmd=ping app1
cmd=telnet app1 22
cmd=telnet app1 80
cmd=telnet app1 443
newline # in ra một dòng mới để phân tách các check

[CHECK:db1]
cmd=ping dns
cmd=telnet dns 53
newline # in ra một dòng mới để phân tách các check
cmd=ping db2
cmd=telnet db2 3306
newline # in ra một dòng mới để phân tách các check

[CHECK:db2]
cmd=ping dns
cmd=telnet dns 53
newline # in ra một dòng mới để phân tách các check
cmd=ping db1
cmd=telnet db1 3306
newline # in ra một dòng mới để phân tách các check
