# Simple test config for v2 format

[HOST:local]
type=local

[HOST:google]
type=external
ip=google.com

[HOST:dns]
type=external
ip=8.8.8.8

[CHECK:local]
cmd=ping dns
cmd=ping google
cmd=telnet google 443

